"""Extract constant issue/unit metadata from the pinned device source, offline."""
import argparse, hashlib, pathlib, re

def generate(reference, output):
    path = reference / 'core/hw/sh4/sh4_opcode_list.cpp'
    source = path.read_text()
    masks = {name: int(value, 16) for name, value in re.findall(r'#define (Mask_\w+) (0x[\da-fA-F]+)', source)}
    reios = (reference / 'core/reios/reios.h').read_text()
    trap = int(re.search(r'#define REIOS_OPCODE (0x[\da-fA-F]+)', reios)[1], 16)
    units = {name: index for index, name in enumerate(['MT', 'EX', 'BR', 'LS', 'FE', 'CO'])}
    table = [5] * 65536  # Missing opcode: CO, zero issue cycles.
    body = source.split('static sh4_opcodelistentry opcodes[]=')[1].split('\n};', 1)[0]
    rows = 0
    for line in body.splitlines():
        line = line.strip()
        if line == '{' or not line.startswith('{') or line.startswith('{0,0,0,0,ReadWritePC}'):
            continue
        match = re.match(r'\{[^,]+,[^,]+,\s*(Mask_\w+)\s*,\s*(0x[\da-fA-F]+|REIOS_OPCODE)\s*,[^,]+,\s*"[^"]*"\s*,\s*(\d+)\s*,\s*\d+\s*,\s*(MT|EX|BR|LS|FE|CO)\s*,', line)
        if not match:
            raise ValueError('Unparsed opcode descriptor: ' + line)
        mask, base, issue, unit = match.groups()
        mask = masks[mask]
        base = trap if base == 'REIOS_OPCODE' else int(base, 16)
        value = units[unit] | (int(issue) << 8)
        for opcode in range(65536):
            if opcode & mask == base:
                table[opcode] = value
        rows += 1
    if rows < 200:
        raise ValueError('Incomplete opcode table')
    text = '// SPDX-License-Identifier: GPL-2.0-or-later\n'
    text += '// Generated by generate_static_timing.py from Flycast opcode descriptors.\n'
    text += '// Source SHA256: ' + hashlib.sha256(path.read_bytes()).hexdigest() + '\n'
    text += '#pragma once\n#include <stdint.h>\n#define SC5_STATIC_TIMING 1\n'
    text += 'static const uint16_t native_static_timing[65536] = {\n'
    text += '\n'.join(','.join(str(x) for x in table[i:i+32]) + ',' for i in range(0,65536,32))
    text += '\n};\n'
    output.write_text(text)
    print(f'Generated {rows} descriptors, 65536 opcode timings: {output}')

if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--reference', required=True, type=pathlib.Path)
    ap.add_argument('--output', type=pathlib.Path, default=pathlib.Path(__file__).with_name('native_static_timing.h'))
    args = ap.parse_args()
    generate(args.reference, args.output)
